# Generated by Django 2.0.2 on 2018-02-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuser',
            options={'ordering': ['name', 'surname']},
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
